version: "3"

services:
  fastapi:
    build:
      context: .
    command: uvicorn api.main:app --reload --host 0.0.0.0
    volumes:
      - ./api/:/app/api
    #   - ./frontend:/app/frontend
    ports:
      - 8080:8000
  nginx:
    image: nginx:latest
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./certs:/etc/certs
    depends_on:
      - fastapi
